//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewPane.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewPane.Languages.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Size.
        /// </summary>
        public static string ActualSize_STR {
            get {
                return ResourceManager.GetString("ActualSize_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply &amp; Close.
        /// </summary>
        public static string ApplyAndClose_STR {
            get {
                return ResourceManager.GetString("ApplyAndClose_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background removal (applies to color and grayscale images only)..
        /// </summary>
        public static string BackgroundRemovalAppliesToColorAndGrayscale_STR {
            get {
                return ResourceManager.GetString("BackgroundRemovalAppliesToColorAndGrayscale_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Name: .
        /// </summary>
        public static string BaseName_STR {
            get {
                return ResourceManager.GetString("BaseName_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black border removal (applies to bitonal images only)..
        /// </summary>
        public static string BlackBorderRemovalAppliesToBitonalImagesOnly_STR {
            get {
                return ResourceManager.GetString("BlackBorderRemovalAppliesToBitonalImagesOnly_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black speckles only.
        /// </summary>
        public static string BlackSpecklesOnly_STR {
            get {
                return ResourceManager.GetString("BlackSpecklesOnly_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Part: .
        /// </summary>
        public static string BookPart_STR {
            get {
                return ResourceManager.GetString("BookPart_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both black and white speckles.
        /// </summary>
        public static string BothBlackAndWhiteSpeckles_STR {
            get {
                return ResourceManager.GetString("BothBlackAndWhiteSpeckles_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness: .
        /// </summary>
        public static string Brightness_STR {
            get {
                return ResourceManager.GetString("Brightness_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_STR {
            get {
                return ResourceManager.GetString("Cancel_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access original image file.
        /// </summary>
        public static string CanTAccessOriginalImageFile_STR {
            get {
                return ResourceManager.GetString("CanTAccessOriginalImageFile_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access preview file.
        /// </summary>
        public static string CanTAccessPreviewFile_STR {
            get {
                return ResourceManager.GetString("CanTAccessPreviewFile_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access reduced image file.
        /// </summary>
        public static string CanTAccessReducedImageFile_STR {
            get {
                return ResourceManager.GetString("CanTAccessReducedImageFile_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find any active Scan Sets!.
        /// </summary>
        public static string CanTFindAnyActiveScanSets_STR {
            get {
                return ResourceManager.GetString("CanTFindAnyActiveScanSets_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change settings.
        /// </summary>
        public static string ClickToChangeSettings_STR {
            get {
                return ResourceManager.GetString("ClickToChangeSettings_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close_STR {
            get {
                return ResourceManager.GetString("Close_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast: .
        /// </summary>
        public static string Contrast_STR {
            get {
                return ResourceManager.GetString("Contrast_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created: .
        /// </summary>
        public static string Created_STR {
            get {
                return ResourceManager.GetString("Created_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despeckle (applies to bitonal images only)..
        /// </summary>
        public static string DespeckleAppliesToBitonalImagesOnly_STR {
            get {
                return ResourceManager.GetString("DespeckleAppliesToBitonalImagesOnly_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despeckle Mask Size:.
        /// </summary>
        public static string DespeckleDlg_Description_STR {
            get {
                return ResourceManager.GetString("DespeckleDlg_Description_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despeckle.
        /// </summary>
        public static string DespeckleDlg_FormTitle_STR {
            get {
                return ResourceManager.GetString("DespeckleDlg_FormTitle_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despeckle Options:.
        /// </summary>
        public static string DespeckleDlg_Options_STR {
            get {
                return ResourceManager.GetString("DespeckleDlg_Options_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled_STR {
            get {
                return ResourceManager.GetString("Enabled_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Image.
        /// </summary>
        public static string FitImage_STR {
            get {
                return ResourceManager.GetString("FitImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Width.
        /// </summary>
        public static string FitWidth_STR {
            get {
                return ResourceManager.GetString("FitWidth_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fore Edge.
        /// </summary>
        public static string ForeEdge_STR {
            get {
                return ResourceManager.GetString("ForeEdge_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Cover.
        /// </summary>
        public static string FrontCover_STR {
            get {
                return ResourceManager.GetString("FrontCover_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front End Papers.
        /// </summary>
        public static string FrontEndPapers_STR {
            get {
                return ResourceManager.GetString("FrontEndPapers_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Free End Paper.
        /// </summary>
        public static string FrontFreeEndPaper_STR {
            get {
                return ResourceManager.GetString("FrontFreeEndPaper_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Pastdown End Paper.
        /// </summary>
        public static string FrontPastdownEndPaper_STR {
            get {
                return ResourceManager.GetString("FrontPastdownEndPaper_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma: .
        /// </summary>
        public static string Gamma_STR {
            get {
                return ResourceManager.GetString("Gamma_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Edge.
        /// </summary>
        public static string HeadEdge_STR {
            get {
                return ResourceManager.GetString("HeadEdge_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file path.
        /// </summary>
        public static string ImageFilePath_STR {
            get {
                return ResourceManager.GetString("ImageFilePath_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert function..
        /// </summary>
        public static string InvertFunction_STR {
            get {
                return ResourceManager.GetString("InvertFunction_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply To:.
        /// </summary>
        public static string IpDlg_ApplyTo_STR {
            get {
                return ResourceManager.GetString("IpDlg_ApplyTo_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Removal.
        /// </summary>
        public static string IpDlg_BackgroundRemoval_STR {
            get {
                return ResourceManager.GetString("IpDlg_BackgroundRemoval_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Border Removal.
        /// </summary>
        public static string IpDlg_BbRemoval_STR {
            get {
                return ResourceManager.GetString("IpDlg_BbRemoval_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despeckle Mask:.
        /// </summary>
        public static string IpDlg_DespeckleMask_STR {
            get {
                return ResourceManager.GetString("IpDlg_DespeckleMask_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Processing.
        /// </summary>
        public static string IpDlg_FormTitle_STR {
            get {
                return ResourceManager.GetString("IpDlg_FormTitle_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despeckle.
        /// </summary>
        public static string IpDlg_GroupDespeckle_STR {
            get {
                return ResourceManager.GetString("IpDlg_GroupDespeckle_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string IpDlg_GroupInvert_STR {
            get {
                return ResourceManager.GetString("IpDlg_GroupInvert_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string IpDlg_GroupRotation_STR {
            get {
                return ResourceManager.GetString("IpDlg_GroupRotation_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation:.
        /// </summary>
        public static string IpDlg_Rotation_STR {
            get {
                return ResourceManager.GetString("IpDlg_Rotation_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is invalid!.
        /// </summary>
        public static string IsInvalid_STR {
            get {
                return ResourceManager.GetString("IsInvalid_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None_STR {
            get {
                return ResourceManager.GetString("None_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal_STR {
            get {
                return ResourceManager.GetString("Normal_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rotation..
        /// </summary>
        public static string NoRotation_STR {
            get {
                return ResourceManager.GetString("NoRotation_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok_STR {
            get {
                return ResourceManager.GetString("Ok_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other_STR {
            get {
                return ResourceManager.GetString("Other_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page ID: .
        /// </summary>
        public static string PageID_STR {
            get {
                return ResourceManager.GetString("PageID_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to display first image.
        /// </summary>
        public static string PressToDisplayFirstImage_STR {
            get {
                return ResourceManager.GetString("PressToDisplayFirstImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to display last image.
        /// </summary>
        public static string PressToDisplayLastImage_STR {
            get {
                return ResourceManager.GetString("PressToDisplayLastImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to display next image.
        /// </summary>
        public static string PressToDisplayNextImage_STR {
            get {
                return ResourceManager.GetString("PressToDisplayNextImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to display previous image.
        /// </summary>
        public static string PressToDisplayPreviousImage_STR {
            get {
                return ResourceManager.GetString("PressToDisplayPreviousImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to fit image.
        /// </summary>
        public static string PressToFitImage_STR {
            get {
                return ResourceManager.GetString("PressToFitImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to fit width.
        /// </summary>
        public static string PressToFitWidth_STR {
            get {
                return ResourceManager.GetString("PressToFitWidth_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to make clips on current image the same size..
        /// </summary>
        public static string PressToMakeClipsOnCurrentImageTheSameSize_STR {
            get {
                return ResourceManager.GetString("PressToMakeClipsOnCurrentImageTheSameSize_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to rotate image -1º.
        /// </summary>
        public static string PressToRotateImage1_STR {
            get {
                return ResourceManager.GetString("PressToRotateImage1_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to rotate image 180º.
        /// </summary>
        public static string PressToRotateImage180_STR {
            get {
                return ResourceManager.GetString("PressToRotateImage180_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to rotate image 90º.
        /// </summary>
        public static string PressToRotateImage90_STR {
            get {
                return ResourceManager.GetString("PressToRotateImage90_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to rotate image +1º.
        /// </summary>
        public static string PressToRotateImagePlus1_STR {
            get {
                return ResourceManager.GetString("PressToRotateImagePlus1_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to scan image.
        /// </summary>
        public static string PressToScanImage_STR {
            get {
                return ResourceManager.GetString("PressToScanImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to see original size.
        /// </summary>
        public static string PressToSeeOriginalSize_STR {
            get {
                return ResourceManager.GetString("PressToSeeOriginalSize_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to zoom in.
        /// </summary>
        public static string PressToZoomIn_STR {
            get {
                return ResourceManager.GetString("PressToZoomIn_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to zoom out.
        /// </summary>
        public static string PressToZoomOut_STR {
            get {
                return ResourceManager.GetString("PressToZoomOut_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear Cover.
        /// </summary>
        public static string RearCover_STR {
            get {
                return ResourceManager.GetString("RearCover_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear End Papers.
        /// </summary>
        public static string RearEndPapers_STR {
            get {
                return ResourceManager.GetString("RearEndPapers_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear Free End Paper.
        /// </summary>
        public static string RearFreeEndPaper_STR {
            get {
                return ResourceManager.GetString("RearFreeEndPaper_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear Pastdown End Paper.
        /// </summary>
        public static string RearPastdownEndPaper_STR {
            get {
                return ResourceManager.GetString("RearPastdownEndPaper_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90° rotation..
        /// </summary>
        public static string Rotation_STR {
            get {
                return ResourceManager.GetString("Rotation_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180° rotation..
        /// </summary>
        public static string Rotation2_STR {
            get {
                return ResourceManager.GetString("Rotation2_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 270° rotation..
        /// </summary>
        public static string Rotation3_STR {
            get {
                return ResourceManager.GetString("Rotation3_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan ID: .
        /// </summary>
        public static string ScanID_STR {
            get {
                return ResourceManager.GetString("ScanID_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to adjust book fold leading points.
        /// </summary>
        public static string SelectToAdjustBookFoldLeadingPoints_STR {
            get {
                return ResourceManager.GetString("SelectToAdjustBookFoldLeadingPoints_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to adjust content clips.
        /// </summary>
        public static string SelectToAdjustContentClips_STR {
            get {
                return ResourceManager.GetString("SelectToAdjustContentClips_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to allow the current page size to be changed without affecting other page sizes..
        /// </summary>
        public static string SelectToAllowTheCurrentPageSizeToBeChanged_STR {
            get {
                return ResourceManager.GetString("SelectToAllowTheCurrentPageSizeToBeChanged_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to be able to select image area.
        /// </summary>
        public static string SelectToBeAbleToSelectImageArea_STR {
            get {
                return ResourceManager.GetString("SelectToBeAbleToSelectImageArea_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to choose zoom in area.
        /// </summary>
        public static string SelectToChooseZoomInArea_STR {
            get {
                return ResourceManager.GetString("SelectToChooseZoomInArea_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to choose zoom out area.
        /// </summary>
        public static string SelectToChooseZoomOutArea_STR {
            get {
                return ResourceManager.GetString("SelectToChooseZoomOutArea_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to display left page.
        /// </summary>
        public static string SelectToDisplayLeftPage_STR {
            get {
                return ResourceManager.GetString("SelectToDisplayLeftPage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to display right page.
        /// </summary>
        public static string SelectToDisplayRightPage_STR {
            get {
                return ResourceManager.GetString("SelectToDisplayRightPage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to dynamicly change zoom.
        /// </summary>
        public static string SelectToDynamiclyChangeZoom_STR {
            get {
                return ResourceManager.GetString("SelectToDynamiclyChangeZoom_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to edit finger zones.
        /// </summary>
        public static string SelectToEditFingersZones_STR {
            get {
                return ResourceManager.GetString("SelectToEditFingersZones_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to move image.
        /// </summary>
        public static string SelectToMoveImage_STR {
            get {
                return ResourceManager.GetString("SelectToMoveImage_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spine Cover.
        /// </summary>
        public static string SpineCover_STR {
            get {
                return ResourceManager.GetString("SpineCover_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail Edge.
        /// </summary>
        public static string TailEdge_STR {
            get {
                return ResourceManager.GetString("TailEdge_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown_STR {
            get {
                return ResourceManager.GetString("Unknown_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White speckles only.
        /// </summary>
        public static string WhiteSpecklesOnly_STR {
            get {
                return ResourceManager.GetString("WhiteSpecklesOnly_STR", resourceCulture);
            }
        }
    }
}
